<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
<HEAD>
<META http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<TITLE>Molière : Iconographie - La référence sur l'oeuvre de Molière - Actualités, Chronologie, Dictionnaire, Oeuvres, Bibliographie, Filmographie</TITLE>
<META NAME="description" lang="fr" CONTENT="Le site de référence sur l'oeuvre de Molière
Ce site, conçu dans un esprit de rigueur scientifique, est destiné à un public large. Aux étudiants ou lycéens qui recherchent des éléments d'information relatifs à Molière ; aux curieux et aux amateurs de théâtre qui s'intéressent à notre dramaturge, et aux chercheurs qui y trouveront un certain nombre d'outils de travail commodes.">
<META NAME="keywords" lang="fr" CONTENT="Molière, Moliere, Jean-Baptiste Poquelin, théâtre, XVII° siècle, Louis XIV, illustre théatre, comédiens, oeuvres, œuvres, textes, pièces, comédie, tragédie, oeuvres de Moliere, dramaturgie, théâtre français, littérature classique, livre, représentation, comédie française, vie de Molière, chronologie, biographie, auteur, acteur, troupe, compagnie, mise en scène, portrait, bibliogaphie, filmographie, dictionnaire, avare, theatre, tartuffe, fourberies de scapin, ecrivain, poesie, bourgeois gentilhomme, théâtre molière, scapin, Molière Biographie, comédie française, Dom Juan, actualite théâtre, comedia del arte, commedia dell'arte, spectacle,bac français, theatre, theatre prose, lettres, preparation bac français">
<meta name="abstract" content="Le site de référence sur l'oeuvre de Molière
Ce site, conçu dans un esprit de rigueur scientifique, est destiné à un public large. Aux étudiants ou lycéens qui recherchent des éléments d'information relatifs à Molière ; aux curieux et aux amateurs de théâtre qui s'intéressent à notre dramaturge, et aux chercheurs qui y trouveront un certain nombre d'outils de travail commodes.">
<meta name="reply-to" content="webmaster@toutmoliere.net">
<meta name="category" content="literature">
<meta name="revisit-after" content="30 days">
<meta name="identifier-url" content="http://www.toutmoliere.net/">
<meta name="robots" content="index, follow">
<meta name="distribution" content="global">
<META NAME="Author" CONTENT="PHENIX Ingénierie Informatique - PEZENAS">
</HEAD>
<FRAMESET COLS="165,*" FRAMESPACING=0 BORDER=0 FRAMEBORDER=no>
  <FRAMESET ROWS="220,*">
    <FRAME NAME=titre SRC="iconograph0.html" SCROLLING=no MARGINWIDTH=0 MARGINHEIGHT=0 NORESIZE FRAMEBORDER=no>
    <FRAME NAME=menu SRC="menu.html" MARGINWIDTH=0 MARGINHEIGHT=0 NORESIZE FRAMEBORDER=no>
  </FRAMESET>
  <FRAME NAME=main SRC="iconographie.php" MARGINWIDTH=0 MARGINHEIGHT=0 NORESIZE FRAMEBORDER=no>
<NOFRAMES>
<BODY>

<h1>Iconographie</h1>
<h2>images, portraits et gravures du XVIIe siècle relatifs à Molière et au théâtre de son temps.</h2>
<h3>Personnages</h3>
<A HREF="images/002.jpg" target="_blank">A. Béjart</A> <A HREF="images/032.jpg" target="_blank">Comédiens italiens</A> <A HREF="images/013.jpg" target="_blank">Farceurs dansants</A> <A HREF="images/023.jpg" target="_blank">Gassendi</A> <A HREF="images/073.jpg" target="_blank">Gros-Guillaume et Gaultier-Garguille</A> <A HREF="images/006.jpg" target="_blank">Jean de Rotrou</A> <A HREF="images/003.jpg" target="_blank">Jodelet</A> <A HREF="images/028.jpg" target="_blank">Julien Bedeau, dit Jodelet.</A> <A HREF="images/040.jpg" target="_blank">L'abbé Cotin</A> <A HREF="images/030.jpg" target="_blank">La Fontaine</A> <A HREF="images/041.jpg" target="_blank">La Reynie</A> <A HREF="images/005.jpg" target="_blank">Louis XIV</A> <A HREF="images/036.jpg" target="_blank">Louis XIV en Apollon</A> <A HREF="images/074.jpg" target="_blank">Louis XIV en campagne</A> <A HREF="images/045.jpg" target="_blank">Lulli</A> <A HREF="images/077.jpg" target="_blank">Marquise Du Parc</A> <A HREF="images/008.jpg" target="_blank">Matamore</A> <A HREF="images/017.jpg" target="_blank">Molière écrivant</A> <A HREF="images/075.jpg" target="_blank">Molière en Arnolphe</A> <A HREF="images/034.jpg" target="_blank">Montfleury</A> <A HREF="images/078.jpg" target="_blank">Nicolas Boileau</A> <A HREF="images/009.jpg" target="_blank">Pierre Corneille</A> <A HREF="images/019.jpg" target="_blank">Pierre Mignard</A> <A HREF="images/076.jpg" target="_blank">Racine</A> <A HREF="images/011.jpg" target="_blank">Scapin</A> <A HREF="images/031.jpg" target="_blank">Scaramouche</A> <A HREF="images/042.jpg" target="_blank">Scaramouche</A> <A HREF="images/027.jpg" target="_blank">Scarron</A> <A HREF="images/035.jpg" target="_blank">Sganarelle</A> <A HREF="images/018.jpg" target="_blank">Tallemant des Réaux</A> <A HREF="images/016.jpg" target="_blank">Tartuffe</A> <A HREF="images/025.jpg" target="_blank">Turlupin</A> <h3>Frontispices des pièces de Molière</h3>
<A HREF="images/048.jpg" target="_blank">Amphitryon</A> <A HREF="images/052.jpg" target="_blank">Dom Garcie de Navarre</A> <A HREF="images/053.jpg" target="_blank">Dom Juan</A> <A HREF="images/059.jpg" target="_blank">Georges Dandin</A> <A HREF="images/047.jpg" target="_blank">L'amour médecin</A> <A HREF="images/061.jpg" target="_blank">L'avare</A> <A HREF="images/054.jpg" target="_blank">L'école des femmes</A> <A HREF="images/055.jpg" target="_blank">L'école des maris</A> <A HREF="images/062.jpg" target="_blank">L'étourdi</A> <A HREF="images/056.jpg" target="_blank">La Comtesse d'Escarbagnas</A> <A HREF="images/050.jpg" target="_blank">La critique de l'école des femmes</A> <A HREF="images/049.jpg" target="_blank">Le bourgeois gentilhomme</A> <A HREF="images/051.jpg" target="_blank">Le dépit amoureux</A> <A HREF="images/063.jpg" target="_blank">Le malade imaginaire</A> <A HREF="images/064.jpg" target="_blank">Le mariage forcé</A> <A HREF="images/065.jpg" target="_blank">Le médecin malgré lui</A> <A HREF="images/039.jpg" target="_blank">Le Misanthrope</A> <A HREF="images/060.jpg" target="_blank">Le Sicilien</A> <A HREF="images/004.jpg" target="_blank">Le Tartuffe</A> <A HREF="images/046.jpg" target="_blank">Les amants magnifiques</A> <A HREF="images/057.jpg" target="_blank">Les fâcheux</A> <A HREF="images/058.jpg" target="_blank">Les femmes savantes</A> <A HREF="images/070.jpg" target="_blank">Les fourberies de Scapin</A> <A HREF="images/068.jpg" target="_blank">Les précieuses ridicules</A> <A HREF="images/067.jpg" target="_blank">M. de Pourceaugnac</A> <A HREF="images/066.jpg" target="_blank">Mélicerte</A> <A HREF="images/069.jpg" target="_blank">Psyché</A> <A HREF="images/071.jpg" target="_blank">Sganarelle</A> <h3>Autres</h3>
<A HREF="images/007.jpg" target="_blank">Affiche de l'Hôtel de Bourgogne</A> <A HREF="images/072.jpg" target="_blank">Andromède</A> <A HREF="images/043.jpg" target="_blank">Comédie-française</A> <A HREF="images/012.jpg" target="_blank">Divertissement Royal</A> <A HREF="images/015.jpg" target="_blank">Elomire hypocondre</A> <A HREF="images/010.jpg" target="_blank">Fauteuil du Malade Imaginaire</A> <A HREF="images/022.jpg" target="_blank">Illustre Théâtre</A> <A HREF="images/001.jpg" target="_blank">Jeu de paume</A> <A HREF="images/021.jpg" target="_blank">Jeu de paume</A> <A HREF="images/038.jpg" target="_blank">Le Cardinal Chigi</A> <A HREF="images/014.jpg" target="_blank">Les plaisirs de l'ile enchantée</A> <A HREF="images/037.jpg" target="_blank">Les plaisirs de l'ile enchantée. Parade</A> <A HREF="images/044.jpg" target="_blank">Les remèdes à tous les maux</A> <A HREF="images/020.jpg" target="_blank">Pézenas</A> <A HREF="images/026.jpg" target="_blank">Registre de La Grange</A> <A HREF="images/024.jpg" target="_blank">Saint-eustache</A> <A HREF="images/033.jpg" target="_blank">Salle du Petit-Bourbon</A> <A HREF="images/029.jpg" target="_blank">Vaux-le-vicomte</A> <h2>Les ressources</h2>
<p><A HREF="../bibliographie/index.php">bibliographie</A> : bibliographie exhaustive, de 5000 articles et manuels, recherche par nom d'auteur, titre, année de parution.</p>
<p><a href="../actualite/index.php">Calendrier et Agenda des manifestations</a> : Les oeuvres de Molière montées durant la saison théâtrale, les colloques, et les livres consacrés à Molière</p>
<p><A HREF="../oeuvres/index.html">oeuvres de Moliere</A> : tous les textes écrits par Molière : pièces de théâtre, préfaces, dédicaces et poésies, d'après les premières éditions conservées à la Bibliothèque Nationale de France;  précédés d'une notice, de notes contenant explications et variantes.</p>
<p><A HREF="../dictionnaire/index.html">dictionnaire</A> : de 300 entrées environ, articles consacrés aux notions dramaturgiques, résumés de pièces, vie intellectuelle et théâtrale du temps, événements biographiques sur Molière, auteurs, acteurs et autres personnages.</p>
<p><a href="../chronologie/index.html">Biographie Moliere</A> : présentés par année (de 1622 à 1682) les événements de la vie de Molière, du monde du théâtre et de la littérature, de la vie politique, du monde des sciences et des arts.</p>
<p><A HREF="../filmographie/index.php">filmographie</A> : documents cinématographiques ou télévisuels, sur la vie de Molière, ou à des mises en scène françaises et étrangères de ses oeuvres.</p>
<p><a href="../index.html">Tout sur Moliere</a></p>
</BODY>
</NOFRAMES>
</FRAMESET>
</HTML>
